- name: create 10 nginx containers for load balancing aon all managed nodes
  hosts: all
  tasks:
   - name: creaye 10 nginx co tainers
     docker_container:
      image: nginx
      name: "container{{item}}"
     with_sequence: count=10
