- name: Installing necessary s/w packages
  hosts: all
  tasks:
   - name: Install s/w packages
     apt: 
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: default-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
      - {a: tomcat8,b: yes}
      - {a: tomcat8-admin,b: no}
- name: Continuous Download and Build
  hosts: DevServer
  tasks:
   - name: download the code from github
     git:
      repo: https://github.com/selenium-saikrishna/maven.git
      dest: /home/ubuntu/mygit
   - name: Build the code
     shell: cd /home/ubuntu/mygit;mvn package
   - name: Fetch artifact from dev to controller
     fetch:
      src: /home/ubuntu/mygit/webapp/target/webapp.war
      dest: /tmp
